image:
  file: .gitpod.Dockerfile

tasks:
  - before: |
      curl -LO https://github.com/protocolbuffers/protobuf/releases/download/v21.12/protoc-21.12-linux-x86_64.zip
      unzip protoc-21.12-linux-x86_64.zip -d $HOME/.local
      export PATH="$PATH:$HOME/.local/bin"
      rm protoc-21.12-linux-x86_64.zip
  - init: yarn install && cd src-tauri && cargo build --no-default-features
    command: "yarn tauri dev"

ports:
  - name: VNC UI
    port: 6080
    onOpen: open-browser

github:
  prebuilds:
    addCheck: true
