[[permission]]
identifier = "allow-get-game-exe-name"
description = "Enables the get_game_exe_name command without any pre-configured scope."
commands.allow = ["get_game_exe_name"]

[[permission]]
identifier = "deny-get-game-exe-name"
description = "Denies the get_game_exe_name command without any pre-configured scope."
commands.deny = ["get_game_exe_name"]