[[permission]]
identifier = "allow-get-current-path"
description = "Enables the check_if_installed command without any pre-configured scope."
commands.allow = ["get_current_path"]

[[permission]]
identifier = "deny-get-current-path"
description = "Denies the check_if_installed command without any pre-configured scope."
commands.deny = ["get_current_path"]