name: Android release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  android_release:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v5
      - name: Set Sparus-sample as default store file
        run: mv src-tauri/Sparus-sample.json src-tauri/Sparus.json
      - name: setup node
        uses: actions/setup-node@v5
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-linux-android
      - name: install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          local-cache: true
      # TODO check after https://github.com/nttld/setup-ndk/issues/518 is fixed
      - name: Restore Android Symlinks
        run: |
          directory="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
          find "$directory" -type l | while read link; do
              current_target=$(readlink "$link")
              new_target="$directory/$(basename "$current_target")"
              ln -sf "$new_target" "$link"
              echo "Changed $(basename "$link") from $current_target to $new_target"
          done
      - name: Install pnpm deps
        run: pnpm install
      - name: Prettier
        run: pnpm prettier
      - name: Lint
        run: pnpm lint
      - name: Build interface
        run: pnpm build
      - name: fmt
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check
      - name: Clippy
        run: cargo clippy --manifest-path=src-tauri/Cargo.toml --all-targets --all-features -- -D warnings
      - name: build Apk
        run: pnpm tauri android build --target aarch64 --split-per-abi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          STRONGHOLD_SALT: ${{ secrets.STRONGHOLD_SALT }}
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - uses: filippoLeporati93/android-release-signer@v1
        name: Sign app APK
        id: sign_app
        with:
          releaseDirectory: src-tauri/gen/android/app/build/outputs/apk/arm64/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          BUILD_TOOLS_VERSION: "34.0.0"
      - name: Upload file
        uses: softprops/action-gh-release@v2
        with:
          files: ${{steps.sign_app.outputs.signedReleaseFile}}
