name: Android build

on:
  push:
    branches:
      - android
  pull_request:
    branches:
      - android

jobs:
  android_build:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18
      - uses: dtolnay/rust-toolchain@master
      - name: install Linux dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev webkit2gtk-4.1
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
      - name: Setup NDK
        uses: nttld/setup-ndk@v1
        id: setup-ndk
        with:
          ndk-version: r25b
          local-cache: true
      # TODO check after https://github.com/nttld/setup-ndk/issues/518 is fixed
      - name: Restore Android Symlinks
        run: |
          directory="${{ steps.setup-ndk.outputs.ndk-path }}/toolchains/llvm/prebuilt/linux-x86_64/bin"
          find "$directory" -type l | while read link; do
              current_target=$(readlink "$link")
              new_target="$directory/$(basename "$current_target")"
              ln -sf "$new_target" "$link"
              echo "Changed $(basename "$link") from $current_target to $new_target"
          done
      - name: Install yarn deps
        run: yarn
      - name: Build interface
        run: yarn build
      - name: Clippy
        run: cargo clippy --manifest-path=src-tauri/Cargo.toml --all-targets --all-features -- -D warnings
      - name: Init Android project 
        run: yarn tauri android init
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: build Apk
        run: yarn tauri android build --target aarch64 --split-per-abi
        env:
          NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: find apk
        run: ls src-tauri/gen/android/app/build/outputs/apk/
      - uses: r0adkll/sign-android-release@v1
        name: Sign app APK
        # ID used to access action output
        id: sign_app
        with:
          releaseDirectory: src-tauri/gen/android/app/build/outputs/apk/arm64/release/
          signingKeyBase64: ${{ secrets.SIGNING_KEY }}
          alias: ${{ secrets.ALIAS }}
          keyStorePassword: ${{ secrets.KEY_STORE_PASSWORD }}
          keyPassword: ${{ secrets.KEY_PASSWORD }}
        env:
          # override default build-tools version (33.0.0) -- optional
          BUILD_TOOLS_VERSION: "34.0.0"
      - uses: actions/upload-artifact@v4
        with:
          name: Sparus-apk.zip
          path: ${{steps.sign_app.outputs.signedReleaseFile}}
          if-no-files-found: error
