name: Clippy Fmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  Clippy:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: install deps
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libappindicator3-dev librsvg2-dev patchelf
      - name: install deps and build frontend 
        run: yarn && yarn build
      - name: Clippy
        run: cargo clippy --manifest-path=src-tauri/Cargo.toml --all-targets --all-features -- -D warnings
  fmt:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Fmt
        run: cargo fmt --manifest-path src-tauri/Cargo.toml --all -- --check
